server: 
  port: 9090
  
encrypt-type: # 0：普通， 1：国密
  encrypt-type: 0

group-channel-connections-config:
  caCert: ca.crt
  sslCert: sdk.crt
  sslKey: sdk.key
  all-channel-connections:
     #group ID
    - group-id: 1
      connections-str:
        # 若节点小于v2.3.0版本，查看配置项listen_ip:channel_listen_port
        - 172.16.60.3:20200 # node channel_listen_ip:channel_listen_port
        - 172.16.60.3:20201
    - group-id: 2
      connections-str:
        # 若节点小于v2.3.0版本，查看配置项listen_ip:channel_listen_port
        - 172.16.60.3:20202 # node channel_listen_ip:channel_listen_port
        - 172.16.60.3:20203
channel-service:
  group-id: 1 # sdk实际连接的群组
  agency-name: fisco # 机构名称